name: Vercel定时重部署
on:
  schedule:
    # cron是UTC时间！！下面示例：每天UTC 0点，等于北京时间8点
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动点按钮立即测试

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: curl -X POST ${{ secrets.VERCEL_REDEPLOY_HOOK }}
